# Generated by Django 4.2.25 on 2025-10-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nome')),
                ('code', models.CharField(help_text='Formato: ABC-123 (checksum: soma dígitos % 3 == 0)', max_length=10, unique=True, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preço')),
                ('category', models.CharField(choices=[('eletronicos', 'Eletrônicos'), ('livros', 'Livros'), ('moveis', 'Móveis'), ('roupas', 'Roupas'), ('alimentos', 'Alimentos')], max_length=100, verbose_name='Categoria')),
                ('subcategory', models.CharField(blank=True, max_length=100, verbose_name='Subcategoria')),
                ('stock', models.IntegerField(default=0, verbose_name='Estoque')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
                'ordering': ['-created_at'],
            },
        ),
    ]
