# Generated by Django 4.2.13 on 2025-10-31 21:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('low_stock_min', models.PositiveIntegerField(default=0, editable=False)),
                ('low_stock_max', models.PositiveIntegerField(default=10)),
                ('medium_stock_min', models.PositiveIntegerField(default=11, editable=False)),
                ('medium_stock_max', models.PositiveIntegerField(default=50)),
                ('high_stock_min', models.PositiveIntegerField(default=51, editable=False)),
                ('high_stock_max', models.PositiveIntegerField(default=999999, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
